const recipes = [
  {
    name: "Crispy Garden Toss",
    description:
      "A refreshing medley of roasted and raw vegetables tossed in a tangy lemon-herb vinaigrette. Perfect for using up assorted greens, crunchy bits, and last-chance produce from the fridge.",
    ingredients: [
      "1 cup cherry tomatoes, halved",
      "1 bell pepper, sliced",
      "1/2 cucumber, sliced",
      "1 carrot, shredded",
      "2 cups mixed greens",
      "1 tbsp olive oil",
      "1 tsp lemon juice",
      "1/2 tsp dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Toss cherry tomatoes and bell peppers in half the olive oil and a pinch of salt.",
      "Roast for 10-15 minutes until slightly charred.",
      "In a large bowl, combine cucumber, shredded carrot, and mixed greens.",
      "Add roasted vegetables once cooled.",
      "Whisk together remaining olive oil, lemon juice, oregano, salt, and pepper.",
      "Pour the dressing over the salad and toss to combine.",
      "Serve immediately.",
    ],
  },
  {
    name: "One-Pot Pantry Pasta",
    description:
      "A cozy, customizable pasta dish made entirely from pantry staples like canned tomatoes, garlic, olive oil, and whatever protein or veggies you have on hand. Minimal dishes, maximum flavor.",
    ingredients: [
      "8 oz dry pasta",
      "2 tbsp olive oil",
      "3 cloves garlic, minced",
      "1 can (14 oz) diced tomatoes",
      "1 tsp dried basil",
      "1/2 tsp chili flakes (optional)",
      "Salt and pepper to taste",
      "1/2 onion, chopped",
      "Optional: canned beans, tuna, or frozen vegetables",
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat.",
      "Add chopped onion and garlic, sauté until fragrant.",
      "Stir in diced tomatoes and bring to a simmer.",
      "Add dried pasta and enough water to just cover.",
      "Season with basil, chili flakes, salt, and pepper.",
      "Simmer uncovered, stirring occasionally, until pasta is al dente and liquid is mostly absorbed (10–12 minutes).",
      "Mix in beans, tuna, or veggies in the last 5 minutes if using.",
      "Adjust seasoning and serve hot.",
    ],
  },
  {
    name: "Wrap Hack Supreme",
    description:
      "A fully loaded flatbread wrap stuffed with leftovers, quick-cooked fillings, and a drizzle of homemade sauce. Fold it, toast it, and enjoy a handheld meal that’s fast and flexible.",
    ingredients: [
      "1 large tortilla or flatbread",
      "1/4 cup cooked rice or grains",
      "1/4 cup cooked beans or lentils",
      "1/4 cup chopped vegetables (lettuce, tomato, onion, etc.)",
      "2 tbsp shredded cheese",
      "1 tbsp mayonnaise or yogurt",
      "1 tsp hot sauce or ketchup",
      "1 tsp olive oil or butter (for toasting)",
    ],
    instructions: [
      "Lay the flatbread on a clean surface and cut a slit from the center to the edge.",
      "Divide the ingredients into 4 sections on the wrap.",
      "In a small bowl, mix mayo/yogurt with hot sauce to make a simple sauce.",
      "Drizzle the sauce on one of the sections.",
      "Fold each section over itself to form a triangle-style wrap.",
      "Heat oil/butter in a skillet over medium heat.",
      "Toast the wrap on both sides until golden and crispy.",
      "Serve warm.",
    ],
  },
  {
    name: "Veggie Fusion Skillet",
    description:
      "A hearty, one-pan vegetarian dish that brings together sautéed seasonal vegetables, tender legumes, and warm spices. Perfectly adaptable to whatever's in your crisper drawer — comfort food with a healthy, plant-based twist.",
    ingredients: [
      "1 tbsp olive oil",
      "1/2 onion, chopped",
      "1 zucchini, diced",
      "1 bell pepper, diced",
      "1 carrot, thinly sliced",
      "1 can chickpeas, drained and rinsed",
      "1 tsp cumin",
      "1/2 tsp smoked paprika",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "Heat olive oil in a large skillet over medium heat.",
      "Add onion and cook until softened.",
      "Add zucchini, bell pepper, and carrot. Sauté for 5–7 minutes.",
      "Stir in chickpeas, cumin, paprika, salt, and pepper.",
      "Cook for another 5 minutes, stirring occasionally.",
      "Garnish with chopped parsley and serve hot.",
    ],
  },
];

export default recipes;
